### ISSUE TITLE
fix start error on missing latest-linux.yml file

### ISSUE THREAD

**Issue by DarkSattis** [DarkSattis/exilence-next#1]
After building following errors happen in the terminal output.

./Exilence-Next-1.1.6.AppImage

(exilence-next-app:110173): dbind-WARNING **: 21:23:44.761: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.systemd1.UnitMasked: Unit at-spi-dbus-bus.service is masked.
21:23:44.847 › App starting...
21:23:44.910 › Checking for update
21:23:44.911 › Checking for update...
21:23:45.157 › Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/viktorgullmark/exilence-next/releases/download/v1.1.6/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/viktorgullmark/exilence-next/releases/download/v1.1.6/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Sun, 28 Nov 2021 20:23:36 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "8278:2967:16411E4:17484B6:61A3E551"
}
    at createHttpError (/tmp/.mount_Exilenv10O2V/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_Exilenv10O2V/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (/tmp/.mount_Exilenv10O2V/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (node:events:394:28)
    at ClientRequest.emit (node:domain:470:12)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:105:6816)
    at SimpleURLLoaderWrapper.emit (node:events:394:28)
    at SimpleURLLoaderWrapper.emit (node:domain:470:12)
    at newError (/tmp/.mount_Exilenv10O2V/resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at GitHubProvider.getLatestVersion (/tmp/.mount_Exilenv10O2V/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:135:50)
    at async AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_Exilenv10O2V/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:498:13)
    at async AppImageUpdater.doCheckForUpdates (/tmp/.mount_Exilenv10O2V/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:514:20)

**Comment by DarkSattis** [comment]
https://github.com/electron-userland/electron-builder/issues/2736 seems related

**Comment by DarkSattis** [comment]
this is actually a warning only, as its a sha512 checksum verification

**Comment by SenselessA** [comment]
same problem
